"""init

Revision ID: 253ef84a2936
Revises: 0ceb2ef3e835
Create Date: 2024-11-30 15:53:16.845144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "253ef84a2936"
down_revision: Union[str, None] = "0ceb2ef3e835"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
